USE [master]
GO

/****** Object:  Database [MyDb]    Script Date: 29.12.2021 13:18:19 ******/
CREATE DATABASE [MyDb]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'MyDb', FILENAME = N'M:\Programy\SQLServer2019\MSSQL15.MSSQLSERVER\MSSQL\DATA\MyDb.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'MyDb_log', FILENAME = N'M:\Programy\SQLServer2019\MSSQL15.MSSQLSERVER\MSSQL\DATA\MyDb_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [MyDb].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [MyDb] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [MyDb] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [MyDb] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [MyDb] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [MyDb] SET ARITHABORT OFF 
GO

ALTER DATABASE [MyDb] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [MyDb] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [MyDb] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [MyDb] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [MyDb] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [MyDb] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [MyDb] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [MyDb] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [MyDb] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [MyDb] SET  DISABLE_BROKER 
GO

ALTER DATABASE [MyDb] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [MyDb] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [MyDb] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [MyDb] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [MyDb] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [MyDb] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [MyDb] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [MyDb] SET RECOVERY FULL 
GO

ALTER DATABASE [MyDb] SET  MULTI_USER 
GO

ALTER DATABASE [MyDb] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [MyDb] SET DB_CHAINING OFF 
GO

ALTER DATABASE [MyDb] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [MyDb] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [MyDb] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [MyDb] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [MyDb] SET QUERY_STORE = OFF
GO

ALTER DATABASE [MyDb] SET  READ_WRITE 
GO

